gem install abbrev
gem install actioncable
gem install actionmailbox
gem install actionmailer
gem install actionpack
gem install actiontext
gem install actionview
gem install activejob
gem install activemodel
gem install activerecord
gem install activestorage
gem install activesupport
gem install addressable
gem install adsf
gem install ai4r
gem install airbrussh
gem install algolia
gem install aliyun-sdk
gem install ansi
gem install arbre
gem install arel
gem install artoo
gem install artoo-sphero
gem install ast
gem install astrolabe
gem install async_sinatra
gem install atomos
gem install autoprefixer-rails
gem install aws-ses
gem install babel-source
gem install babel-transpiler
gem install backports
gem install base64
gem install bcrypt
gem install benchmark
gem install better_errors
gem install bigdecimal
gem install bindex
gem install binding_of_caller
gem install bootstrap-sass
gem install bootstrap-will_paginate
gem install bouncy-castle-java
gem install bourbon
gem install brakeman
gem install buftok
gem install builder
gem install bundler
gem install bundler-unload
gem install byebug
gem install capistrano
gem install capistrano-bundler
gem install capistrano-harrow
gem install capistrano-rails
gem install capistrano-rvm
gem install capistrano3-puma
gem install capybara
gem install carrierwave
gem install celluloid
gem install celluloid-essentials
gem install celluloid-extras
gem install celluloid-fsm
gem install celluloid-io
gem install celluloid-pool
gem install celluloid-supervision
gem install CFPropertyList
gem install cgi
gem install childprocess
gem install chronic
gem install chunky_png
gem install claide
gem install climate_control
gem install cmath
gem install cocaine
gem install cocoapods-deintegrate
gem install cocoapods-downloader
gem install cocoapods-plugins
gem install cocoapods-search
gem install cocoapods-stats
gem install cocoapods-trunk
gem install cocoapods-try
gem install coderay
gem install coffee-rails
gem install coffee-script
gem install coffee-script-source
gem install colored
gem install colored2
gem install colorize
gem install columnize
gem install commonjs
gem install compass
gem install compass-core
gem install compass-import-once
gem install concurrent-ruby
gem install connection_pool
gem install cookiejar
gem install countries
gem install country_select
gem install cowsay
gem install crass
gem install cri
gem install csv
gem install csv2api
gem install cucumber
gem install cucumber-core
gem install cucumber-create-meta
gem install cucumber-cucumber-expressions
gem install cucumber-expressions
gem install cucumber-html-formatter
gem install cucumber-messages
gem install cucumber-rails
gem install cucumber-tag-expressions
gem install cucumber-tag_expressions
gem install cucumber-wire
gem install currencies
gem install daemons
gem install database_cleaner
gem install database_cleaner-active_record
gem install database_cleaner-core
gem install date
gem install dbm
gem install ddmemoize
gem install ddmetrics
gem install ddplugin
gem install debug
gem install debug_inspector
gem install debugger-linecache
gem install declarative
gem install declarative-option
gem install delegate
gem install descendants_tracker
gem install devise
gem install devise_invitable
gem install devise_token_auth
gem install did_you_mean
gem install diff-lcs
gem install docile
gem install dogapi
gem install domain_name
gem install dotenv
gem install drb
gem install dropbox-sdk
gem install dry-inflector
gem install e2mmap
gem install elasticsearch
gem install elasticsearch-api
gem install elasticsearch-model
gem install elasticsearch-rails
gem install elasticsearch-transport
gem install em-http-request
gem install em-socksify
gem install em-websocket
gem install email_spec
gem install english
gem install equalizer
gem install erb
gem install erubi
gem install erubis
gem install escape
gem install etc
gem install ethon
gem install excon
gem install execjs
gem install executable-hooks
gem install factory_girl
gem install factory_girl_rails
gem install faker
gem install faraday
gem install faraday-net_http
gem install fastercsv
gem install faye
gem install faye-websocket
gem install fcntl
gem install ffi
gem install ffi-compiler
gem install fiddle
gem install figaro
gem install fileutils
gem install find
gem install fission
gem install flog
gem install flowdock
gem install fog
gem install fog-aliyun
gem install fog-atmos
gem install fog-aws
gem install fog-brightbox
gem install fog-cloudatcost
gem install fog-cloudstack
gem install fog-core
gem install fog-digitalocean
gem install fog-dnsimple
gem install fog-dynect
gem install fog-ecloud
gem install fog-google
gem install fog-internet-archive
gem install fog-joyent
gem install fog-json
gem install fog-local
gem install fog-openstack
gem install fog-ovirt
gem install fog-powerdns
gem install fog-profitbricks
gem install fog-rackspace
gem install fog-radosgw
gem install fog-riakcs
gem install fog-sakuracloud
gem install fog-serverlove
gem install fog-softlayer
gem install fog-storm_on_demand
gem install fog-terremark
gem install fog-vmfusion
gem install fog-voxel
gem install fog-vsphere
gem install fog-xenserver
gem install fog-xml
gem install formatador
gem install formtastic
gem install formtastic-bootstrap
gem install forwardable
gem install foundation-rails
gem install fourflusher
gem install friendly_id
gem install fuubar
gem install fuzzy_match
gem install gas
gem install gdbm
gem install gem-wrappers
gem install gems
gem install geocoder
gem install getoptlong
gem install gh_inspector
gem install gherkin
gem install gherkin3
gem install git
gem install github
gem install globalid
gem install google-api-client
gem install google-apis-core
gem install google-apis-discovery_v1
gem install google-apis-generator
gem install google-cloud-env
gem install google-protobuf
gem install googleauth
gem install grease
gem install growl
gem install guard
gem install guard-compat
gem install guard-cucumber
gem install guard-livereload
gem install guard-minitest
gem install guard-rails
gem install guard-rspec
gem install guard-rubocop
gem install guard-spork
gem install haml
gem install hamster
gem install has_scope
gem install hashie
gem install highline
gem install hike
gem install hirb
gem install hitimes
gem install homesick
gem install htmlentities
gem install http
gem install http-accept
gem install http-cookie
gem install http-form_data
gem install http-parser
gem install http_parser.rb
gem install httparty
gem install httpclient
gem install hybridgroup-argus
gem install i18n
gem install i18n_data
gem install image_processing
gem install inflecto
gem install inherited_resources
gem install interception
gem install io-console
gem install io-nonblock
gem install io-wait
gem install ipaddr
gem install ipaddress
gem install irb
gem install jaro_winkler
gem install jbuilder
gem install journey
gem install jquery-rails
gem install jquery-turbolinks
gem install jruby-openssl
gem install json
gem install json_pure
gem install json_schema
gem install jwt
gem install kaminari
gem install kaminari-actionview
gem install kaminari-activerecord
gem install kaminari-core
gem install kgio
gem install kramdown
gem install launchy
gem install less
gem install less-rails
gem install libnotify
gem install listen
gem install little-plugger
gem install logger
gem install logging
gem install loofah
gem install lumberjack
gem install mail
gem install marcel
gem install maruku
gem install matrix
gem install memoist
gem install memoizable
gem install metaclass
gem install method_source
gem install middleware
gem install mime-types
gem install mime-types-data
gem install mimemagic
gem install mini_magick
gem install mini_mime
gem install mini_portile
gem install mini_portile2
gem install minitest
gem install minitest-reporters
gem install mocha
gem install molinillo
gem install monetize
gem install money
gem install money-rails
gem install multi_json
gem install multi_test
gem install multi_xml
gem install multipart-post
gem install mustermann
gem install mutex_m
gem install nanaimo
gem install nanoc
gem install nanoc-checking
gem install nanoc-cli
gem install nanoc-core
gem install nanoc-deploying
gem install nap
gem install naught
gem install nenv
gem install net-ftp
gem install net-ftp-list
gem install net-http
gem install net-http-persistent
gem install net-imap
gem install net-pop
gem install net-protocol
gem install net-scp
gem install net-sftp
gem install net-smtp
gem install net-ssh
gem install net-telnet
gem install netrc
gem install nio4r
gem install nkf
gem install nokogiri
gem install nokogumbo
gem install notiffany
gem install nyan-cat-formatter
gem install observer
gem install open-uri
gem install open3
gem install open4
gem install openssl
gem install optimist
gem install optparse
gem install orm_adapter
gem install os
gem install ostruct
gem install ovirt-engine-sdk
gem install pagerduty
gem install paperclip
gem install parallel
gem install parser
gem install pastel
gem install path_expander
gem install pathname
gem install pdf-core
gem install pdfkit
gem install pg-hstore
gem install pkg-config
gem install plugin_manager
gem install polyamorous
gem install polyglot
gem install power_assert
gem install powerpack
gem install pp
gem install prawn
gem install prettyprint
gem install prime
gem install private_pub
gem install protobuf-cucumber
gem install pry
gem install pry-byebug
gem install pry-rails
gem install pry-rescue
gem install pry-stack_explorer
gem install pstore
gem install psych
gem install public_suffix
gem install puma
gem install pygments.rb
gem install quiet_assets
gem install racc
gem install rack
gem install rack-cache
gem install rack-livereload
gem install rack-protection
gem install rack-ssl
gem install rack-test
gem install rails
gem install rails-controller-testing
gem install rails-deprecated_sanitizer
gem install rails-dom-testing
gem install rails-html-sanitizer
gem install rails-observers
gem install rails_12factor
gem install rails_apps_composer
gem install rails_serve_static_assets
gem install rails_stdout_logging
gem install railties
gem install rainbow
gem install raindrops
gem install rake
gem install ransack
gem install rb-fsevent
gem install rb-inotify
gem install rb-kqueue
gem install rbovirt
gem install rbs
gem install rbvmomi
gem install rchardet
gem install rdoc
gem install readline
gem install readline-ext
gem install redcar
gem install redcar-bundles
gem install redcar-icons
gem install redcar-javamateview
gem install redcar-jruby
gem install redcar-svnkit
gem install reel
gem install ref
gem install regexp_parser
gem install reline
gem install representable
gem install resolv
gem install resolv-replace
gem install responders
gem install rest-client
gem install retriable
gem install rexml
gem install rgeo
gem install rgeo-activerecord
gem install right_aws
gem install right_http_connection
gem install rinda
gem install robeaux
gem install rspec
gem install rspec-core
gem install rspec-expectations
gem install rspec-logsplit
gem install rspec-mocks
gem install rspec-rails
gem install rspec-support
gem install rss
gem install rubocop
gem install rubocop-ast
gem install ruby-blockcache
gem install ruby-macho
gem install ruby-progressbar
gem install ruby-vips
gem install ruby2_keywords
gem install ruby2ruby
gem install ruby_gntp
gem install ruby_parser
gem install rubygems-bundler
gem install rubygems-update
gem install rubyserial
gem install rubyzip
gem install rvm
gem install safe_yaml
gem install sanitize
gem install sass
gem install sass-listen
gem install sass-rails
gem install sassc
gem install sassc-rails
gem install scanf
gem install sdbm
gem install sdoc
gem install securerandom
gem install selenium-webdriver
gem install set
gem install sexp_processor
gem install shell
gem install shellany
gem install shellwords
gem install signet
gem install simple_form
gem install simple_oauth
gem install simplecov
gem install simplecov-html
gem install simplecov-rcov
gem install simplecov_json_formatter
gem install sinatra
gem install sinatra-respond_to
gem install singleton
gem install sixarm_ruby_unaccent
gem install slim
gem install slop
gem install slow_enumerator_tools
gem install sort_alphabetical
gem install sphero
gem install spoon
gem install spork
gem install spork-rails
gem install spring
gem install spring-commands-rspec
gem install spring-watcher-listen
gem install sprockets
gem install sprockets-es6
gem install sprockets-rails
gem install spruz
gem install sqlite3
gem install squeel
gem install sshkit
gem install ssrf_filter
gem install stringio
gem install strscan
gem install swt
gem install sync
gem install sys-uname
gem install syslog
gem install tempfile
gem install temple
gem install term-ansicolor
gem install terminal-notifier-guard
gem install terminal-table
gem install terrapin
gem install test-unit
gem install text-format
gem install text-hyphen
gem install thin
gem install thor
gem install thread_safe
gem install thwait
gem install tilt
gem install time
gem install timecop
gem install timeout
gem install timers
gem install tins
gem install tmpdir
gem install tomlrb
gem install tracer
gem install treetop
gem install trollop
gem install tsort
gem install ttfunk
gem install tty-color
gem install tty-command
gem install tty-platform
gem install tty-which
gem install turbolinks
gem install turbolinks-source
gem install twitter
gem install twitter-bootstrap-rails
gem install typeprof
gem install typhoeus
gem install tzinfo
gem install uber
gem install uglifier
gem install un
gem install unf
gem install unf_ext
gem install unicode-display_width
gem install unicode_utils
gem install unicorn
gem install uri
gem install vcr
gem install warden
gem install weakref
gem install web-console
gem install webrick
gem install websocket
gem install websocket-driver
gem install websocket-extensions
gem install websocket_parser
gem install whenever
gem install wicked_pdf
gem install will_paginate
gem install workload
gem install xcodeproj
gem install xml-simple
gem install xmlrpc
gem install xpath
gem install yaml
gem install yard
gem install zeitwerk
gem install zlib
