gem install actioncable
gem install actionmailer
gem install actionpack
gem install actionview
gem install activejob
gem install activemodel
gem install activerecord
gem install activesupport
gem install addressable
gem install adsf
gem install ai4r
gem install airbrussh
gem install arbre
gem install arel
gem install ast
gem install astrolabe
gem install atomic
gem install autoprefixer-rails
gem install aws-ses
gem install babel-source
gem install babel-transpiler
gem install backports
gem install bcrypt
gem install better_errors
gem install bigdecimal
gem install binding_of_caller
gem install bootstrap-sass
gem install bootstrap-will_paginate
gem install bouncy-castle-java
gem install bourbon
gem install brakeman
gem install buftok
gem install builder
gem install bundler
gem install bundler-unload
gem install byebug
gem install capistrano
gem install capistrano-bundler
gem install capistrano-harrow
gem install capistrano-rails
gem install capistrano-rvm
gem install capistrano3-puma
gem install capybara
gem install celluloid
gem install celluloid-essentials
gem install celluloid-extras
gem install celluloid-fsm
gem install celluloid-io
gem install celluloid-pool
gem install celluloid-supervision
gem install CFPropertyList
gem install childprocess
gem install chronic
gem install chunky_png
gem install climate_control
gem install cocaine
gem install coderay
gem install coffee-rails
gem install coffee-script
gem install coffee-script-source
gem install colored
gem install colorize
gem install columnize
gem install compass
gem install compass-core
gem install compass-import-once
gem install concurrent-ruby
gem install cookiejar
gem install countries
gem install country_select
gem install cowsay
gem install cri
gem install csv2api
gem install cucumber
gem install cucumber-core
gem install cucumber-rails
gem install cucumber-wire
gem install currencies
gem install database_cleaner
gem install debug_inspector
gem install debugger-linecache
gem install descendants_tracker
gem install devise
gem install did_you_mean
gem install diff-lcs
gem install docile
gem install dogapi
gem install domain_name
gem install dotenv
gem install dropbox-sdk
gem install elasticsearch
gem install elasticsearch-api
gem install elasticsearch-model
gem install elasticsearch-rails
gem install elasticsearch-transport
gem install em-http-request
gem install em-socksify
gem install em-websocket
gem install email_spec
gem install equalizer
gem install erubis
gem install eventmachine
gem install excon
gem install execjs
gem install executable-hooks
gem install factory_girl
gem install factory_girl_rails
gem install faker
gem install faraday
gem install fastercsv
gem install faye
gem install faye-websocket
gem install ffi
gem install figaro
gem install fission
gem install flog
gem install flowdock
gem install formatador
gem install formtastic
gem install formtastic-bootstrap
gem install foundation-rails
gem install friendly_id
gem install fuubar
gem install gas
gem install gem-wrappers
gem install geocoder
gem install gherkin
gem install gherkin3
gem install git
gem install github
gem install globalid
gem install growl
gem install guard
gem install guard-compat
gem install guard-cucumber
gem install guard-livereload
gem install guard-rails
gem install guard-rspec
gem install guard-rubocop
gem install guard-spork
gem install haml
gem install hamster
gem install has_scope
gem install hashie
gem install highline
gem install hike
gem install hirb
gem install hitimes
gem install homesick
gem install htmlentities
gem install http
gem install http-cookie
gem install http-form_data
gem install http_parser.rb
gem install httparty
gem install hybridgroup-argus
gem install i18n
gem install i18n_data
gem install inflecto
gem install inherited_resources
gem install interception
gem install io-console
gem install ipaddress
gem install jbuilder
gem install journey
gem install jquery-rails
gem install jquery-turbolinks
gem install jruby-openssl
gem install json
gem install json_pure
gem install kaminari
gem install kgio
gem install kramdown
gem install launchy
gem install libnotify
gem install listen
gem install loofah
gem install lucene
gem install lumberjack
gem install mail
gem install memoizable
gem install metaclass
gem install method_source
gem install mime-types
gem install mime-types-data
gem install mimemagic
gem install mini_portile
gem install mini_portile2
gem install minitest
gem install mocha
gem install monetize
gem install money
gem install money-rails
gem install multi_json
gem install multi_test
gem install multi_xml
gem install multipart-post
gem install nanoc
gem install naught
gem install nenv
gem install net-ftp-list
gem install net-scp
gem install net-sftp
gem install net-ssh
gem install net-telnet
gem install nio4r
gem install nokogiri
gem install notiffany
gem install nyan-cat-formatter
gem install open4
gem install orm_adapter
gem install pagerduty
gem install paperclip
gem install parallel
gem install parser
gem install path_expander
gem install pdf-core
gem install pdfkit
gem install pg
gem install pg-hstore
gem install pkg-config
gem install plugin_manager
gem install polyamorous
gem install polyglot
gem install power_assert
gem install powerpack
gem install prawn
gem install private_pub
gem install pry
gem install pry-byebug
gem install pry-rails
gem install pry-rescue
gem install pry-stack_explorer
gem install psych
gem install public_suffix
gem install puma
gem install quiet_assets
gem install rack
gem install rack-cache
gem install rack-livereload
gem install rack-protection
gem install rack-ssl
gem install rack-test
gem install rails
gem install rails-deprecated_sanitizer
gem install rails-dom-testing
gem install rails-html-sanitizer
gem install rails-observers
gem install rails_12factor
gem install rails_apps_composer
gem install rails_serve_static_assets
gem install rails_stdout_logging
gem install railties
gem install rainbow
gem install raindrops
gem install rake
gem install ransack
gem install rb-fsevent
gem install rb-inotify
gem install rdoc
gem install redcar
gem install redcar-bundles
gem install redcar-icons
gem install redcar-javamateview
gem install redcar-jruby
gem install redcar-svnkit
gem install reel
gem install ref
gem install responders
gem install rgeo
gem install rgeo-activerecord
gem install right_aws
gem install right_http_connection
gem install robeaux
gem install rspec
gem install rspec-core
gem install rspec-expectations
gem install rspec-logsplit
gem install rspec-mocks
gem install rspec-rails
gem install rspec-support
gem install rubocop
gem install ruby-blockcache
gem install ruby-progressbar
gem install ruby2ruby
gem install ruby_dep
gem install ruby_gntp
gem install ruby_parser
gem install rubygems-bundler
gem install rubygems-update
gem install rubyzip
gem install rvm
gem install safe_yaml
gem install sass
gem install sass-rails
gem install sdoc
gem install selenium-webdriver
gem install sexp_processor
gem install shellany
gem install simple_form
gem install simple_oauth
gem install simplecov
gem install simplecov-html
gem install simplecov-rcov
gem install sinatra
gem install sixarm_ruby_unaccent
gem install slim
gem install slop
gem install sort_alphabetical
gem install spoon
gem install spork
gem install spork-rails
gem install spring
gem install spring-commands-rspec
gem install sprockets
gem install sprockets-es6
gem install sprockets-rails
gem install spruz
gem install sqlite3
gem install squeel
gem install sshkit
gem install swt
gem install temple
gem install term-ansicolor
gem install terminal-notifier-guard
gem install terminal-table
gem install test-unit
gem install text-format
gem install text-hyphen
gem install thor
gem install thread_safe
gem install tilt
gem install timecop
gem install timers
gem install tins
gem install treetop
gem install ttfunk
gem install turbolinks
gem install turbolinks-source
gem install twitter
gem install tzinfo
gem install uglifier
gem install unf
gem install unf_ext
gem install unicode-display_width
gem install unicode_utils
gem install unicorn
gem install vcr
gem install warden
gem install web-console
gem install websocket
gem install websocket-driver
gem install websocket-extensions
gem install websocket_parser
gem install whenever
gem install wicked_pdf
gem install will_paginate
gem install workload
gem install xml-simple
gem install xpath
gem install yard
